---
apiVersion: v1
kind: Service
metadata:
  name: splunk-defaults 
  #namespace: splunk
  labels:
    app: splunk
    tier: management 
spec:
  #type: LoadBalancer
  selector:
    name: splunk-defaults
  ports:
    - name: nginx-web
      port: 80
      targetPort: 80
  clusterIP: None
