version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: splunk-debian-9
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
      - SPLUNK_HEC_TOKEN=abcd1234
      - DEBUG=true
    ports:
      - 8000
      - 8089
      - 8088
