version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  uf1:
    image: splunk/universalforwarder:latest
    hostname: uf1
    container_name: uf1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - DEBUG=true
      - SPLUNK_ADD=udp 1514,monitor /var/log/*
      - DOCKER_MONITORING=true
      - SPLUNK_PASSWORD
    ports:
      - 8089
