version: 2
jobs:
  setup:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup python3
          command: |
            pyenv global 2.7.12 3.5.2
            python --version
            pip --version
            python3 --version
            pip3 --version
      - run:
          name: Setup Tests / Scanner Requirements
          command: |
            make test_setup
      - run:
          name: Build Container
          command: |
            make all
  security-scanning:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Run Vulnerability Scanner
          command: |
            make setup_and_run_clair
      - store_artifacts:
          name: Store Scanner Logs
          path: clair-scanner-logs
          destintation: clair-scanner-logs
      - store_artifacts:
          path: test-results
          destination: test-results
  debian10-testing:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Test if image size increase
          command: make test_debian10_image_size
      - run:
          name: Run small Debian 10 image tests
          command: make run_small_tests_debian10
          no_output_timeout: 20m
      - run:
          name: Run large Debian 10 image tests
          command: make run_large_tests_debian10
          no_output_timeout: 20m
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  redhat8-testing:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Run small Redhat 8 image tests
          command: make run_small_tests_redhat8
          no_output_timeout: 20m
      - run:
          name: Run large Redhat 8 image tests
          command: make run_large_tests_redhat8
          no_output_timeout: 20m
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  container-validation:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Export Build Images for Artifacts
          command: |
            make save_containers
      - run:
          name: Test Python3 installation
          command: make test_python3_all
      - run:
          name: Test Python2 as the default
          command: make test_python2_all
      - store_artifacts:
          path: test-results
          destination: test-results
workflows:
  version: 2
  build:
    jobs:
      - setup
      - security-scanning:
          requires:
            - setup
      - debian10-testing:
          requires:
            - setup
      - container-validation:
          requires:
            - setup
      - redhat8-testing:
          requires:
            - setup