version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    branches:
      only:
        - master
        - circleci
    steps:
      - checkout
      - run:
          name: run tests
          command: make test
