---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-master-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

